# This is a basic workflow that is manually triggered

name: backup

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pwsh:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Backup
        shell: powershell
        run: Write-Host (Get-Location).Path

    
    
