name: CI (code)

on:
  push:
    branches:
      - 'master'
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '.github/workflows/**'
      - 'theme/**'
      - 'Program.cs'
  pull_request:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '.github/workflows/**'
      - 'theme/**'
      - 'Program.cs'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: .NET Info
        run: dotnet --info

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Run generator (no build)
        run: dotnet run --configuration Release --no-build

      - name: Archive output (for inspection)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: site-output
          path: ./output
