# This is a basic workflow to help you get started with Actions

name: Deploy

# Automatic deploy on push to master, manual dispatch still available.
on:
  push:
    branches:
      - 'master'
    paths:
      - 'input/**'
  # Allow manual runs from the Actions UI
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore, Build and Run
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet run --configuration Release --no-build

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Clear storage container (safe)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} -s '$web' --if-match '*'

      - name: Upload site files
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} -d '$web' -s ./output
            az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} -d '$web' -s ./output --pattern "*.html" --content-type text/html

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths "/*" --profile-name "${{ secrets.CDN_PROFILE_NAME }}" --name "${{ secrets.CDN_ENDPOINT }}" --resource-group "${{ secrets.RESOURCE_GROUP }}"

      - name: Azure Logout
        run: az logout
